FORMAT: 1A
HOST: http://private-ebed2-bartender4.apiary-mock.com

# API_bartender

「てのひらバーテンダー」のAPIです。

## ユーザ [/users]

### 新規登録 [POST]

#### 処理概要

* ユーザを新しく登録する。

+ Request (application/json)

    + body

            {
                "user_id":{
                    "user_name": "user",
                    "login_id": "1234",
                    "login_pw": "abc123"
                }
            }

+ Response 201 (application/json)   

    + body

            {
                "bool":true
            }

+ Response 400 (application/json) 

    + body

            {
                "bool": false
            }

## ログイン [/login]

### ログイン情報取得 [POST]

+ Request (application/json)

    + body

            {
                "user_id":{
                    "login_id": "12234",
                    "login_pw": "abc123"
                }
            }

+ Response 201 (application/json)   

    + body

            {
                "bool":true
            }
                
+ Response 400 (application/json) 

    + body

            {
                "bool": false
            }
    

## 質問 [/question/{ques_id}]

### 質問表示 [POST]

+ Parameters
    + ques_id: 1 (number)

+ Request (application/json)

    + body

            {
                "answer_id":[
                    "option_contents1": "赤”, 
                    "option_contents2": "青”, 
                    "option_contents3": "黄色”
                ]
            }


+ Response 201 (application/json)

    + body

            {
                "ques_id":{
                    "ques_contens": "好きな色は何ですか？",
                    "option_id":[
                            "option_contents1": "赤”,
                            "option_contents2": "青,
                            "option_contents3": "黄色”
                        ]
                }
            }


## カクテル [/alcohols]

### カクテル詳細 [POST]

+ Request (application/json)

    + body

            {
                "alco_name": "ジン・トニック"
            }

+ Response 201 (application/json)

    + body

            {
                "alco_id":{
                    "type_name": "カクテルの説明"
                    "alco_name": "ジン・トニック"
            }

## 履歴 [/history]

### 履歴 [GET]

+ Response 200 (application/json)

    + body

            {
                "history1": {
                    "history_id": 2,
                    "user_id": 1,
                    "alco_name": "カシスオレンジ",
                    "data_joined": "2018-11-11T11:26:45.629566+00:00",
                    "review": 5
                },
                "history2": {
                    "history_id": 3,
                    "user_id": 1,
                    "alco_name": "カシスグレープ",
                    "data_joined": "2018-11-11T11:56:29.312260+00:00",
                    "review": null
                },
                "history3": {
                    "history_id": 1,
                    "user_id": 1,
                    "alco_name": "オレンジブロッサム",
                    "data_joined": "2018-11-11T11:57:08.802710+00:00",
                    "review": 5
                },
                "history4": {
                    "history_id": 4,
                    "user_id": 1,
                    "alco_name": "モヒート",
                    "data_joined": "2018-11-11T12:01:06.170376+00:00",
                    "review": 5
                },
                "history5": {
                    "history_id": 5,
                    "user_id": 3,
                    "alco_name": "キール",
                    "data_joined": "2018-11-11T12:03:35.983323+00:00",
                    "review": null
                },
                "history6": {
                    "history_id": 6,
                    "user_id": 3,
                    "alco_name": "ファジーネーブル",
                    "data_joined": "2018-11-11T12:35:17.860670+00:00",
                    "review": 4
                }
            }


### 履歴 [POST]

+ Request (application/json)

    + body

            {
                "alco_name": "ファジーネーブル"
            }

+ Response 201 (application/json)

    + body

            {
                "message": "履歴を保存しました"
            }

## レビュー [/review]

### レビュー [PUT]

+ Request (application/json)

    + body

            {
                "alco_name": "ファジーネーブル",
                "review": 4
            }

+ Response 200 (application/json)   

    + body

            {
                "message":"レビューを更新しました"
            }

### レビュー [POST]

+ Request (application/json)

    + body

            {
                "alco_name": "ファジーネーブル"
            }

+ Response 200 (application/json)   

    + body

            {
                "history_id": 6,
                    "user_id": 1,
                    "alco_name": "ファジーネーブル",
                    "data_joined": ,
                    "review": 4
            }