version: '3'
services:
  web:
    container_name: web
    restart: always
    build: ./Docker/Web
    command: sh -c "sleep 10; ./manage.py runserver 0.0.0.0:8000" 
    volumes:
      - ./src:/code
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./Docker/PostgreSQL/dbdata:/var/lib/postgresql/data"
      - ./Docker/PostgreSQL/SQL:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: bar
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: bartender