# Generated by Django 2.1.1 on 2018-11-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('alcohol_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField()),
                ('alco_name', models.CharField(max_length=20)),
                ('image', models.TextField(blank=True, null=True)),
                ('detail', models.TextField()),
            ],
            options={
                'db_table': 'alcohol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_data', models.TextField(blank=True, null=True)),
                ('learning_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('alco_name', models.CharField(max_length=20)),
                ('data_joined', models.DateTimeField()),
                ('review', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_contents1', models.CharField(max_length=30)),
                ('option_contents2', models.CharField(max_length=30)),
                ('option_contents3', models.CharField(blank=True, max_length=30, null=True)),
                ('option_contents4', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('ques_contents', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
    ]
