#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Generated by Django 2.1.1 on 2018-10-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20181007_2057'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='alcohol',
            table='alcohol',
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
        migrations.AlterModelTable(
            name='option',
            table='option',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
