# Generated by Django 2.1.1 on 2018-11-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('last_login', models.DateTimeField()),
            ],
            options={
                'db_table': 'account',
                'managed': False,
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
